# .goreleaser.yml
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - 
    id: serveo
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: ./cmd/serveo
    ldflags:
      - -s -w
nfpms:
  -
    id: serveo
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      amd64: 64-bit
      386: 32-bit
      darwin: macOS
      linux: Linux
    vendor: Ax333l
    homepage: https://github.com/Axelen123/serveo
    maintainer: Ax333l
    builds:
      - serveo
    description: Unofficial serveo.net CLI
    license: MIT
    formats:
      - deb
    dependencies:
      - openssh-client
    bindir: /usr/bin
snapcrafts:
  -
    id: serveo
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      amd64: 64-bit
      386: 32-bit
      darwin: macOS
      linux: Linux
    builds:
      - serveo
    summary: Unofficial serveo.net CLI
    description: Unofficial serveo.net CLI
    license: MIT
    confinement: strict
    base: core18
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
