language: go
addons:
  apt:
    packages:
    - rpm
    - snapd
git:
  depth: 1
go:
- 1.12.x
env: 
  global: 
    PATH: /snap/bin:$PATH
    GO111MODULE: on
    secure: c9ba70glmdiHk1iDmLH46jJkgdbDFF0ygpKuZ08LJIhu4xWC/7/Gly80g+CmJZNc7BMSbLBMQVJHQI3w56R4VUprhr22Qk2bGU+j5hfiM2brnRhgfJrxtyW9eWFq7jg7uCpJjXC+jze0+9ptpFdMR+aUMSb8Vg6xB0iozCcGJnQn3Zvf6EJf8q6/dqQHPTpi2XGdJu8f9ZEP+JHCAoc5oCvFuqwDVQed7vfO6044Ur6BX0D92AMdaolINcXnBkrWFltUIKf+mEEIsPYGHpHTG1ed8izJUm+4F2sS2sBDfviATF5mAhBpJXRHQlF/eWydW+TGNfTHfqzkjkFVVlFwyZl1NmMTXC2M7BLQXZsM7BuGVMjkQCLTfLPkvhe4O2unDiP9NBcx4Veaa6owBxXTDvhmSSgPG2GfsRDmYZCebWPgTDeAUzwPPXofR3qH1ZKqwrM1z4s9UxI/fLLDvMjcP+Azv8nc1Up5HSbNrUknhj/esk6qhz/UYWLj5HWMgoruwhKCqNg4sYrQQ1fOBkP6Uvtb2SLZMMWnTnpE8Dfm9imDluYm4VZeeOcIoAqLdJCYXVXAbitt+jQopM9Od1u0cpP/dPL0hCNKR1lZYpOBJ3Wv5P9QQPS27UfSM41sTbwUc2rQqeXHGfrgy6hzOTKpFHRpOfUAJrTuGgEDL6e2tkY=
install: sudo snap install snapcraft --classic
services:
- docker
after_success:
- test -n "$TRAVIS_TAG" && docker login -u=myuser -p="$DOCKER_PASSWORD"
- test -n "$TRAVIS_TAG" && snapcraft login --with snap.login
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
before_install:
- openssl aes-256-cbc -K $encrypted_576ea288b03a_key -iv $encrypted_576ea288b03a_iv
  -in snap.login.enc -out snap.login -d
