language: go
addons:
  apt:
    packages:
    - rpm
    - snapd
env:
- PATH=/snap/bin:$PATH
install:
- sudo snap install snapcraft --classic
services:
- docker
after_success:
- test -n "$TRAVIS_TAG" && docker login -u=myuser -p="$DOCKER_PASSWORD"
- test -n "$TRAVIS_TAG" && snapcraft login --with snap.login
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
before_install:
- openssl aes-256-cbc -K $encrypted_576ea288b03a_key -iv $encrypted_576ea288b03a_iv
  -in snap.login.enc -out snap.login -d
